name: Dev Workflow

on:
  pull_request_target:
    types:
      - opened
    branches: [ main ]
    
jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build
      run: yarn install
      run: CI='' yarn run build
