name: Production Workflow

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: yarn install

    - name: Deploy
      run: yarn run deploy
