name: Production Workflow

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build
      run: yarn install

    - name: Deploy
      run: |
        git config --global user.name 'Marco Raigoza'
        git config --global user.email 'mraigoza@bu.edu'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        CI='' yarn run deploy
