name: Production Workflow

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install
      run: yarn install

    - name: Build
      run: CI='' yarn run build
